Matriculacion/Controllers/EstudianteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Matriculacion.Models;

namespace Matriculacion.Controllers
{
    public class EstudianteController : Controller
    {
        private MatriculacionEntities db = new MatriculacionEntities();

        // GET: Estudiante
        public ActionResult Index()
        {
            var estudiantes = db.Estudiantes.Include(e => e.Carrera).Include(e => e.Cuatrimestre);
            return View(estudiantes.ToList());
        }

        // GET: Estudiante/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estudiante estudiante = db.Estudiantes.Find(id);
            if (estudiante == null)
            {
                return HttpNotFound();
            }
            return View(estudiante);
        }

        // GET: Estudiante/Create
        public ActionResult Create()
        {
            ViewBag.CarreraId = new SelectList(db.Carreras, "CarreraId", "Descripcion");
            ViewBag.CuatrimestreId = new SelectList(db.Cuatrimestres, "CuatrimestreId", "Descripcion");
            return View();
        }

        // POST: Estudiante/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EstudianteId,CuatrimestreId,CarreraId,Matricula,Nombre,Apellido,Cedula,Correo,Telefono,Direccion,Contrasena,ContrasenaC")] Estudiante estudiante)
        {
            if (ModelState.IsValid)
            {
                db.Estudiantes.Add(estudiante);
                db.SaveChanges();
                return RedirectToAction("Login","Home");
            }

            ViewBag.CarreraId = new SelectList(db.Carreras, "CarreraId", "Descripcion", estudiante.CarreraId);
            ViewBag.CuatrimestreId = new SelectList(db.Cuatrimestres, "CuatrimestreId", "Descripcion", estudiante.CuatrimestreId);
            return View(estudiante);
        }

        // GET: Estudiante/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estudiante estudiante = db.Estudiantes.Find(id);
            if (estudiante == null)
            {
                return HttpNotFound();
            }
            ViewBag.CarreraId = new SelectList(db.Carreras, "CarreraId", "Descripcion", estudiante.CarreraId);
            ViewBag.CuatrimestreId = new SelectList(db.Cuatrimestres, "CuatrimestreId", "Descripcion", estudiante.CuatrimestreId);
            return View(estudiante);
        }

        // POST: Estudiante/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EstudianteId,CuatrimestreId,CarreraId,Matricula,Nombre,Apellido,Cedula,Correo,Telefono,Direccion,Contrasena,ContrasenaC")] Estudiante estudiante)
        {
            if (ModelState.IsValid)
            {
                db.Entry(estudiante).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CarreraId = new SelectList(db.Carreras, "CarreraId", "Descripcion", estudiante.CarreraId);
            ViewBag.CuatrimestreId = new SelectList(db.Cuatrimestres, "CuatrimestreId", "Descripcion", estudiante.CuatrimestreId);
            return View(estudiante);
        }

        // GET: Estudiante/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estudiante estudiante = db.Estudiantes.Find(id);
            if (estudiante == null)
            {
                return HttpNotFound();
            }
            return View(estudiante);
        }

        // POST: Estudiante/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Estudiante estudiante = db.Estudiantes.Find(id);
            db.Estudiantes.Remove(estudiante);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Matriculacion/Controllers/HomeController.cs
using Matriculacion.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Matriculacion.Controllers
{
    public class HomeController : Controller
    {
        private MatriculacionEntities db = new MatriculacionEntities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            Session["CuatrimestreId"] = null;
            Session["EstudianteId"] = null;
            Session["CarreraId"] = null;
            Session["Nombre"] = null;
            Session["Admin"] = null;
            Session["Login"] = null;
            return View();
        }
        [HttpPost]
        public ActionResult Login(string Email, string Password)
        {
            var estudiante = db.Estudiantes.Where(a => a.Correo == Email && a.Contrasena == Password).SingleOrDefault();
            var admin = db.Usuarios.Where(a => a.Correo == Email && a.Contrasena == Password).SingleOrDefault();

            if (estudiante != null) {
                Session["CuatrimestreId"] = estudiante.CuatrimestreId;
                Session["EstudianteId"] = estudiante.EstudianteId;
                Session["CarreraId"] = estudiante.CarreraId;
                Session["Nombre"] = estudiante.Nombre +' '+ estudiante.Apellido;
                Session["Admin"] = null;
                Session["Login"] = true;

                return RedirectToAction("Index", "Home");

            } else if (admin != null) {
                Session["Nombre"] = admin.Nombre +' '+admin.Apellido;
                Session["Admin"] = true;
                Session["Login"] = true;

                return RedirectToAction("Index", "Home");
            }

            return View();
        }
        public ActionResult Register()
        {
            ViewBag.CarreraId = new SelectList(db.Carreras, "CarreraId", "Descripcion");
            ViewBag.CuatrimestreId = new SelectList(db.Cuatrimestres, "CuatrimestreId", "Descripcion");
            return View();
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Matriculacion/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Matriculacion/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Matriculacion/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Sistema de Inscripcion de materias</h1>
    <p class="lead">En este sistema tendras la facilidad de seleccionar tus materias mas facil y rapido que nunca.</p>
    
</div>

Matriculacion/Views/Home/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Log in</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/Content/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/dist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="#"><b>Login</b></a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Inicia sesion como estudiante o admin</p>

                <form action="@Url.Action("Login","Home")" method="post">
                    <div class="input-group mb-3">
                        <input type="email" class="form-control" name="Email" id="Email" placeholder="Email">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" name="Password" id="Password" placeholder="Password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-8">
                            <div class="icheck-primary">
                                <input type="checkbox" id="remember">
                                <label for="remember">
                                    Recuerdame
                                </label>
                            </div>
                        </div>
                        <!-- /.col -->
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Entrar</button>
                        </div>
                        <!-- /.col -->
                    </div>
                </form>
                <!-- /.social-auth-links -->
                <p class="mb-0">
                    <a href="@Url.Action("Register","Home")" class="text-center">Registrarse como nuevo estudiante</a>
                </p>
            </div>
            <!-- /.login-card-body -->
        </div>
    </div>
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/Content/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Content/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/dist/js/adminlte.min.js"></script>
</body>
</html>

Matriculacion/Views/Home/Register.cshtml
@model Matriculacion.Models.Estudiante

@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Registro</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/Content/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/dist/css/adminlte.min.css">
</head>
<body class="hold-transition register-page">
    <div class="register-box">
        <div class="register-logo">
            <a href="#"><b>Registro</b></a>
        </div>

        <div class="card">
            <div class="card-body register-card-body">
                <p class="login-box-msg">Registrarse como estudiante</p>

                @using (Html.BeginForm("Create", "Estudiante"))
                {
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <label>Cuatrimestre</label>
                    <div class="input-group mb-3">
                        @Html.DropDownList("CuatrimestreId", null, htmlAttributes: new { @class = "form-control" })
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-database"></span>
                            </div>
                        </div>
                    </div>
                    <label>Carrera</label>
                    <div class="input-group mb-3">
                        @Html.DropDownList("CarreraId", null, htmlAttributes: new { @class = "form-control" })
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-book"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        @Html.EditorFor(model => model.Matricula, new { htmlAttributes = new { @class = "form-control", @placeholder = "Matricula" } })
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-id-card"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nombre" } })
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-user"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control", @placeholder = "Apellido" } })
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-user"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control", @placeholder = "Cedula" } })
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-id-card"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control", @placeholder = "Correo" } })
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control", @placeholder = "Telefono" } })
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-phone"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control", @placeholder = "Direccion" } })
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-house-user"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" name="Contrasena" id="Contrasena" placeholder="Contraseña">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" name="ContrasenaC" id="ContrasenaC" placeholder="Repita contraseña">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-8">
                            <div class="icheck-primary">
                                <input type="checkbox" id="agreeTerms" name="terms" value="De acuerdo">
                                <label for="agreeTerms">
                                    Estoy de acuerdo con los <a href="#">terminos</a>
                                </label>
                            </div>
                        </div>
                        <!-- /.col -->
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Registrar</button>
                        </div>
                        <!-- /.col -->
                    </div>
                }

                <a href="@Url.Action("Login","Home")" class="text-center">Ya estoy registrado...</a>
            </div>
            <!-- /.form-box -->
        </div><!-- /.card -->
    </div>
    <!-- /.register-box -->
    <!-- jQuery -->
    <script src="~/Content/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Content/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/dist/js/adminlte.min.js"></script>
</body>
</html>