Matriculacion/Models/Cursando.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matriculacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursando
    {
        public int CursandoId { get; set; }
        public Nullable<int> EstudianteId { get; set; }
        public Nullable<int> MateriaId { get; set; }
    
        public virtual Materia Materia { get; set; }
        public virtual Estudiante Estudiante { get; set; }
    }
}

Matriculacion/Controllers/CursandoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Matriculacion.Models;

namespace Matriculacion.Controllers
{
    public class CursandoController : Controller
    {
        private MatriculacionEntities db = new MatriculacionEntities();

        // GET: Cursando
        public ActionResult Index()
        {
            var EstudianteId = Convert.ToInt32(Session["EstudianteId"]);
            var cursandoes = db.Cursandoes.Include(c => c.Estudiante).Include(c => c.Materia).Where(a => a.EstudianteId == EstudianteId);
            return View(cursandoes.ToList());
        }

        // GET: Cursando/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cursando cursando = db.Cursandoes.Find(id);
            if (cursando == null)
            {
                return HttpNotFound();
            }
            return View(cursando);
        }
        public JsonResult MateriaDetalles(int? id)
        {
            if (id == null)
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
            var materia = db.Materias.Where(a => a.MateriaId == id).Select(a => new
            {
                MateriaId = a.MateriaId,
                CarreraId = a.CarreraId,
                Descripcion = a.Descripcion,
                Codigo = a.Codigo,
                Creditos = a.Creditos,
                Imparte = db.Impartes.Where(b => b.MateriaId == a.MateriaId).Select(b => new
                {
                    Profesor = db.Profesors.Where(c => c.ProfesorId == b.ProfesorId).Select(c => new
                    {
                        Nombre = c.Nombre,
                        Apellido = c.Apellido
                    })
                }).ToList()

            });
            if (materia == null)
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }
            return Json(materia, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Eliminar(int? id)
        {
            Cursando cursando = db.Cursandoes.Find(id);
            db.Cursandoes.Remove(cursando);
            db.SaveChanges();
            return Json("OK", JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetMaterias()
        {
            var results = db.Materias.ToList().Select(a => new SelectListItem
            {
                Text = a.Descripcion.ToUpper(),
                Value = a.MateriaId.ToString()
            });
            return this.Json(results.OrderBy(a => a.Text), JsonRequestBehavior.AllowGet);
        }
        public JsonResult Crear(int id)
        {
            if (ModelState.IsValid)
            {
                Cursando cursando = new Cursando();
                cursando.EstudianteId = Convert.ToInt32(Session["EstudianteId"]);
                cursando.MateriaId = id;

                db.Cursandoes.Add(cursando);
                db.SaveChanges();
                return Json("Ok", JsonRequestBehavior.AllowGet);

            }
            return Json("", JsonRequestBehavior.AllowGet);
        }

        // GET: Cursando/Create
        public ActionResult Create()
        {
            int carreraid = Convert.ToInt32(Session["CarreraId"]);
            ViewBag.MateriaId = new SelectList(db.Materias.Where(a => a.CarreraId == carreraid), "MateriaId", "Descripcion");
            return View();
        }

        // POST: Cursando/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CursandoId,EstudianteId,MateriaId")] Cursando cursando)
        {
            if (ModelState.IsValid)
            {
                cursando.EstudianteId = Convert.ToInt32(Session["EstudianteId"]);
                db.Cursandoes.Add(cursando);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EstudianteId = new SelectList(db.Estudiantes, "EstudianteId", "Matricula", cursando.EstudianteId);
            ViewBag.MateriaId = new SelectList(db.Materias, "MateriaId", "Codigo", cursando.MateriaId);
            return View(cursando);
        }

        // GET: Cursando/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cursando cursando = db.Cursandoes.Find(id);
            if (cursando == null)
            {
                return HttpNotFound();
            }
            ViewBag.EstudianteId = new SelectList(db.Estudiantes, "EstudianteId", "Matricula", cursando.EstudianteId);
            ViewBag.MateriaId = new SelectList(db.Materias, "MateriaId", "Codigo", cursando.MateriaId);
            return View(cursando);
        }

        // POST: Cursando/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CursandoId,EstudianteId,MateriaId")] Cursando cursando)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cursando).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EstudianteId = new SelectList(db.Estudiantes, "EstudianteId", "Matricula", cursando.EstudianteId);
            ViewBag.MateriaId = new SelectList(db.Materias, "MateriaId", "Codigo", cursando.MateriaId);
            return View(cursando);
        }


        // GET: Cursando/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cursando cursando = db.Cursandoes.Find(id);
            if (cursando == null)
            {
                return HttpNotFound();
            }
            return View(cursando);
        }

        // POST: Cursando/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cursando cursando = db.Cursandoes.Find(id);
            db.Cursandoes.Remove(cursando);
            db.SaveChanges();
            return RedirectToAction("Index");
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Matriculacion/Views/Cursando/Create.cshtml
@model Matriculacion.Models.Cursando

@{
    ViewBag.Title = "Create";
}
<br />
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Seleccion de Materias </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       
        <div class="form-group">
            
            @Html.LabelFor(model => model.MateriaId, "Materia", htmlAttributes: new { @class = "" })
            <div class="col-md-10">
                @Html.DropDownList("MateriaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MateriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 ">
                <input type="submit" value="Seleccionar" class="btn btn-default" />
                
                  |  @Html.ActionLink("Volver a lista de seleccion ", "Index")
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Matriculacion/Views/Cursando/Delete.cshtml
@model Matriculacion.Models.Cursando

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cursando</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Estudiante.Matricula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estudiante.Matricula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Materia.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Materia.Codigo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Matriculacion/Views/Cursando/Details.cshtml
@model Matriculacion.Models.Cursando

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Cursando</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Estudiante.Matricula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estudiante.Matricula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Materia.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Materia.Codigo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CursandoId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Matriculacion/Views/Cursando/Edit.cshtml
@model Matriculacion.Models.Cursando

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cursando</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CursandoId)

        <div class="form-group">
            @Html.LabelFor(model => model.EstudianteId, "EstudianteId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EstudianteId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EstudianteId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MateriaId, "MateriaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MateriaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MateriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Matriculacion/Views/Cursando/Index.cshtml
@model IEnumerable<Matriculacion.Models.Cursando>

@{
    ViewBag.Title = "Index";
}
<br />
<button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-lg">
    Agregar materias
</button>

<table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                Materia
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Materia.Codigo)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Materia.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Materia.Codigo)
                </td>

                <td>
                    <a class="btn btn-default detalle" data-toggle="modal" data-target="#modal-xl" title="Detalles de la materia" MateriaId="@item.MateriaId"><i class="fas fa-list"></i></a>
                    <a class="btn btn-default Delete" CursandoId="@item.CursandoId" title="Eliminar" href="#"><i class="fas fa-trash"></i></a>
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.CursandoId }) |
                        @Html.ActionLink("Details", "Details", new { id = item.CursandoId }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.CursandoId })*@
                </td>
            </tr>
        }

    </tbody>


</table>

<div class="modal fade" id="modal-xl">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Detalles de la materia</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body row" id="DetalleModal">

            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<div class="modal fade" id="modal-lg">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Seleccion de Materias</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <select class="form-control select2" id="MateriaId" name="MateriaId" style="width:100%">
                    <option value="" selected="selected">SELECCIONE</option>
                </select>
                <br />
                <div class="row" id="ContenidoMateria">

                </div>

            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary SelectMateria" >Seleccionar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');


            $.fn.clearSelect = function () {
                return this.each(function () {
                    if (this.tagName == 'SELECT')
                        this.options.length = 0;
                });
            }
            $.fn.fillSelect = function (data) {
                return this.clearSelect().each(function () {
                    if (this.tagName == 'SELECT') {
                        var dropdownList = this;
                        //Add default Value
                        var option = new Option("SELECCIONE", "");
                        dropdownList.add(option);

                        $.each(data, function (index, optionData) {
                            option = new Option(optionData.Text, optionData.Value);
                            dropdownList.add(option);
                        });
                    }
                });
            }

            $(function () {
                $.getJSON("@Url.Action("GetMaterias", "Cursando")", null, function (data) {
                    $("#MateriaId").fillSelect(data);
                }).then(() => {
                    $('.select2').select2();
                });
            });

            $("#MateriaId").change(function () {
                var MateriaId = $(this).val();

                $.ajax({
                    type: "GET",
                    url: "@Url.Action("MateriaDetalles", "Cursando")",
                    data: { id: MateriaId },
                    contentType: "application/json",
                    dataType: "json",
                    success: function (data) {
                        $('#ContenidoMateria').empty();
                        $('#ContenidoMateria').append(`
                            <div class="col-lg-6">
                                <label>Materia:</label> ${data[0].Descripcion}
                            </div>
                            <div class="col-lg-6">
                                <label>Codigo:</label> ${data[0].Codigo}
                            </div>
                            <div class="col-lg-6">
                                <label>Creditos:</label> ${data[0].Creditos}
                            </div>
                            <div class="col-lg-6">
                                <label>Profesor:</label> ${data[0].Imparte[0].Profesor[0].Nombre} ${data[0].Imparte[0].Profesor[0].Apellido}
                            </div>
                        `);
                    }
                })
            })

            $(".SelectMateria").click(function () {

                var MateriaId = $("#MateriaId").val();
                $(".SelectMateria").prop('disabled', true);
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("Crear", "Cursando")",
                    data: { id: MateriaId },
                    contentType: "application/json",
                    dataType: "json",
                    success: function (data) {
                        if (data == "Ok") {
                            $(function () {
                                var Toast = Swal.mixin({
                                    toast: true,
                                    position: 'top-end',
                                    showConfirmButton: false,
                                    timer: 3000
                                });

                                Toast.fire({
                                    icon: 'success',
                                    title: 'Materia agregada exitosamente.',                                   
                                }).then(function () {
                                    location.reload();
                                });
                            })
                        }
                    }
                })
            })

            $(".Delete").click(function () {

                var CursandoId = $(this).attr('CursandoId');
                $(this).prop('disabled', true);

                $.ajax({
                    type: "GET",
                    url: "@Url.Action("Eliminar", "Cursando")",
                    data: { id: CursandoId },
                    contentType: "application/json",
                    dataType: "json",
                    success: function (data) {
                    if (data == "OK") {
                        $(function () {
                            var Toast = Swal.mixin({
                                toast: true,
                                position: 'top-end',
                                showConfirmButton: false,
                                timer: 2000
                            });
                            Toast.fire({
                                icon: 'success',
                                title: 'Materia eliminada exitosamente.',                              
                            }).then(function () {
                                location.reload();
                            });
                        })
                        }
                    }
                })
            })

            $(".detalle").click(function () {
                var MateriaId = $(this).attr('MateriaId');

                $.ajax({
                    type: "GET",
                    url: "@Url.Action("MateriaDetalles", "Cursando")",
                    data: { id: MateriaId },
                    contentType: "application/json",
                    dataType: "json",
                    success: function (data) {
                        $('#DetalleModal').empty();
                        $('#DetalleModal').append(`
                            <div class="col-lg-6">
                                <label>Materia:</label> ${data[0].Descripcion}
                            </div>
                            <div class="col-lg-6">
                                <label>Codigo:</label> ${data[0].Codigo}
                            </div>
                            <div class="col-lg-6">
                                <label>Creditos:</label> ${data[0].Creditos}
                            </div>
                            <div class="col-lg-6">
                                <label>Profesor:</label> ${data[0].Imparte[0].Profesor[0].Nombre} ${data[0].Imparte[0].Profesor[0].Apellido}
                            </div>
                        `);
                    }
                })

            })
        })
    </script>
}